### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by marijanbeg** [ubermag/mag2exp#1]
The internal code name: exsim

In this issue, we can propose and discuss the name of the package. We have to ensure the name is not already used on: https://pypi.org/ and https://anaconda.org/.

**Comment by lang-m** [comment]
`exsim` (and also `simex`) is already used on pypi.

**Comment by marijanbeg** [comment]
Also `extools`, `exptools`, `experimant` are already taken.

Some available names: `exmag`, `expsim`, `experimenttools`, `uberexperiment`.

**Comment by lang-m** [comment]
I would probably stick to `ubermag...` (if we include anything with `uber` at all). That would be more consistent with other packages in Ubermag.
Some options: `ubermagexperiment`, `ubermagmeasurement`, `ubermagimaging` (maybe not general enough)

**Comment by samjrholt** [comment]
I've been thinking about names which are available:
`magexp`, `magneticexp`, `mag2exp`
I do also like `ubermagexperiment` as it is clear.

**Comment by samjrholt** [comment]
Speaking to a few people it seems like the most popular is `mag2exp` so I think this would be a good final package name unless there are any objections.

**Comment by marijanbeg** [comment]
Sounds good. :)
