### ISSUE TITLE
Use new discretisedfield syntax

### ISSUE THREAD

**Issue by samjrholt** [ubermag/mag2exp#47]

**Comment by lang-m** [comment]
I remember that we had at least one function (I just do not remember which one) where a 2d field was required. Has this changed "automatically" (because the function is using methods in `discretisedfield` that now return lower-dimensional fields)?

**Comment by samjrholt** [comment]
These have automatically changed to a 2d field. There were changes to the code, however these weren't major structural changes and now all of the tests pass. I accidently applied the changes directly to master, hence no linked pull request. Usually I would have gone back and retroactively created a pull request but I thought we have more pressing things to do in the short term.
