### ISSUE TITLE
Base exsim functions on Field object

### ISSUE THREAD

**Issue by marijanbeg** [ubermag/mag2exp#5]
By using `discretisedfield.Field` as an input instead of `numpy.ndarray`, we already have the following functionalities:

1. Mathematical operations
2. Plotting

This way, we avoid:

- code repetition
- simplify exsim code substantially

Missing functionalities in `discretisedfield.Field`:

- FFT (https://github.com/ubermag/discretisedfield/issues/81)

**Comment by lang-m** [comment]
We might also think about completely removing the classe(s) and instead have a number of functions similar to how it is done in  `df.tools`. I already did some tests in the `df-based`-branch.

**Comment by marijanbeg** [comment]
I agree. Probably the design to go with is `result_field = sam_function(m_field, args)`. This way, all the plotting is readily available.

Sorry @lang-m, I did not see you were on a different branch already :( I have not changed any files, I just moved them around a bit, so I hope it is not going to be too painful to merge.
